### PR TITLE
Fix broken links on Streampipes documentation

### PR DESCRIPTION
**Pull request by mohanvive**
### Purpose
There are quite several broken links on Streampipes documentation. I have fixed some based on what I have identified. 

It would be better to run a dead-link validator against the documentation to fix all of them.

### CODE REVIEW

**Comment by mohanvive** [comment]
@dominikriemer For your review

**Review by dominikriemer — APPROVED** [review]
Thanks @mohanvive!
I'll merge your changes and release a new docs version asap.
One comment, the documentation of pipeline elements is auto-generated from the documentation.md file in the extensions project -  if you update the documentation there, we run a script from the streampipes-maven-plugin after every release so that the documentation is updated and new pipeline elements are also added to the list.

**Comment by mohanvive** [comment]
@dominikriemer Quick question based on the response above. What are the steps involved to build the website once I have done the changed to the documentation.md files in incubator-streampipes-extension repo?. 

Even though md files are properly generated, there are some inconsistencies on the generated documentation related to pipeline elements.

**Comment by dominikriemer** [comment]
Sure, happy to help!
This is a rather quick-and-dirty plugin I typically run once after each release, so there might be bugs, but the general process is somehow semi-automatic ;-)

- add the streampipes-maven-plugin to the extensions project
- execute mvn streampipes:extract-docs
- this generates docs for the website & docusaurus pages and rewrites the image paths of the icons mentioned in the markdown files.
- I manually copy the markdown files in target\docs\docs-documentation\pe into the documentation/docs/pe folder of streampipes-website 
- I copy the content of target/docs/sidebars.json into the sidebars.json of the docs repo (after the updates of the documentation structure, this part of the script produces an incorrect output and needs to be changed so that the list is ordered by pipeline element type)
- Images are manually copied from the img folder to the corresponding Docusaurus folder.
- The updated docs are then available for the "next" version in Docusaurus

I assume you already successfully generated the docs and maybe just ran into the issue with the sidebars.json or which kind of inconsistencies did find?

**Comment by dominikriemer** [comment]
@mohanvive I just thought about easing the process..in general, we could change the build script of this repo so that the website build clones the extensions project, builds the docs with the maven plugin and replaces the pipeline element documentations with the auto-generated docs.

What do you think?

**Comment by mohanvive** [comment]
@dominikriemer I have tried the above-provided steps, and they worked perfectly. Even though the live website does not load some documentation content, the local "next" documentation version correctly loads. So I think this could be an issue that arise when deploying the documentation. 

Anyway, I have fixed some issues which I witnessed reproduced. Please find the related PR, https://github.com/apache/incubator-streampipes-extensions/pull/47

**Pull request merged**
