### PR TITLE
Post/release 0.70.0

### PR DESCRIPTION
**Pull request by bossenti**
### Purpose
Preparing the blog post for the upcoming release of version 0.70.0

### CODE REVIEW

**Comment by bossenti** [comment]
@tenthe, @dominikriemer, first of all how do you like using GIFs instead of plain screenshots?
It just come up to my mind when I was writing the blogpost to present the changes that way.
I'm curious to hear what you think about it.
I've created screenshots along the way too, so it would be pretty easy to switch back to our regular way of presentation.
More than that, how do you like the blogpost?
Did I include all the main features and improvements or is something important missing?
Do you agree with the order (importance) of the changes?

Feel free to remark any errors or directly adapt the post accordingly.

**Comment by tenthe** [comment]
Hi Tim,
thanks a lot for providing the blog post.
I read it and made some minor changes, I hope that is ok. 
The GIFs are awsome maybe we can start using these in other places in the documentation as well.
I have only one minor comment. The change to the mono-repo was already part of the last release.
However, we only deprecated the old ones in this release, so you may be able to leave it in. What do you think?

**Comment by bossenti** [comment]
Thanks Philipp for your adjustments.
Ah true, the corresponding JIRA ticket was part of the release, but I should have been skeptical.
I'll remove that section then, I don't think it's worth mentioning that we archived the other repositories.

**Review by dominikriemer — APPROVED** [review]

**Comment by dominikriemer** [comment]
Hi Tim,
great post and the GIF screenshots are awesome.
If you don't mind it would be great to have a short section in the developer wiki which explains how to create these GIFs for future releases, in case there are others like me who don't know how to do this ;-)

**Comment by bossenti** [comment]
Thanks for reviewing, @dominikriemer :) 
Sure, here you go: https://cwiki.apache.org/confluence/display/STREAMPIPES/Record+GIFs+for+release+blog+posts
I will also advertise it on our mailing list once the blog post is online.

FYI: I will update the blog post's date and merge the PR once `0.70.0` is finally available.

**Pull request merged**
